[ui]
icon = "â”"
new_game_icon = "ğŸ“œ"
code_blank_symbol = "ğŸ‡½"
code_symbols = ["ğŸ‡¦", "ğŸ‡§", "ğŸ‡¨", "ğŸ‡©", "ğŸ‡ª", "ğŸ‡«", "ğŸ‡¬", "ğŸ‡­"]
feedback_blank_symbol = "â­•"
feedback_symbols = ["ğŸ”´", "âšª"]
check_default_text = "â”"
check_hover_text = "â“"


[settings]
[settings.language]
label = "Language:"
default_value = "en"
current_value = "en"
options = [
  { value = "en", display_str = "English" },
  { value = "pl", display_str = "Polish" },
]

[settings.variation]
label = "Variation:"
default_value = "original"
current_value = "original"
options = [
  { value = "original", display_str = "original (10 rows, 4 pegs, 6 symbols)" },
  { value = "mini", display_str = "mini (6 rows, 4 pegs, 6 symbols)" },
  { value = "super", display_str = "super (12 rows, 5 pegs, 8 symbols)" },
]

[settings.blank_symbol]
label = "Blank symbol:"
default_value = false
current_value = false

[settings.duplicate_symbols]
label = "Duplicate symbols:"
default_value = false
current_value = false


[variations]
[variations.original]
num_rows = 10
num_pegs = 4
num_symbols = 6

[variations.mini]
num_rows = 6
num_pegs = 4
num_symbols = 6

[variations.super]
num_rows = 12
num_pegs = 5
num_symbols = 8
